name: "🛠 Task"
description: "A development or refactoring task"
labels: ["task", "development"]
body:
  - type: textarea
    id: task-description
    attributes:
      label: "📌 Task Description"
      description: "What needs to be done?"

  - type: input
    id: related-issues
    attributes:
      label: "🔗 Related Issues (Optional)"
      description: "Link any related issues or PRs"

  - type: textarea
    id: subtasks
    attributes:
      label: "✅ Subtasks (Optional)"
      description: "Break down the task into smaller steps"
      placeholder: |
        - [ ] Step 1
        - [ ] Step 2
        - [ ] Step 3

  - type: dropdown
    id: priority
    attributes:
      label: "⚡ Priority"
      options:
        - "Low"
        - "Medium"
        - "High"
    validations:
      required: true
